framework:
  messenger:
    transports:
      async:
        dsn: '%env(RABBITMQ_DSN)%'
        retry_strategy:
          max_retries: 3
          multiplier: 2
      failed: 'doctrine://default?queue_name=failed'

    failure_transport: failed
    routing:
      App\Message\CommentMessage: async
      #Symfony\Component\Mailer\Messenger\SendEmailMessage: async