framework:
    workflows:
      comment:
        type: state_machine
        audit_trail:
          enabled: "%kernel.debug%"
        marking_store:
          type: "method"
          property: "state"
        supports:
          - App\Entity\Comment
        initial_marking: submitted
        places:
          - submitted
          - potential_spam
          - rejected
          - published
        transitions:
          might_be_spam:
            from: submitted
            to: potential_spam
          publish:
            from: potential_spam
            to: published
          reject:
            from: potential_spam
            to: rejected
